Numpy arithmatic operation: 

Addition (+):
You can add two arrays or a scalar to an array:

In [1]:
import numpy as np
x=np.array([1, 2, 3, 4]) # One dimensional array 
y=x+10 # 10 is a scalar, scalar mean the array any value add 10 like 1+10, 2=10, 3+10, 4+10
print(y)

[11 12 13 14]


Two Dimensional array add

In [2]:
array1=np.array([1, 2, 3, 4])
array2=np.array([1, 2, 3, 4])
#Two method use addition two dimensional array 
addition=array1+array2  
addition2=np.add(array1, array2)
print("The one is addition",addition)
print("The second is addition2",addition2)

The one is addition [2 4 6 8]
The second is addition2 [2 4 6 8]


take the value through keybard and use for loop and store the array then add value:

[expression for item in iterable]
expression: What to do with each item (e.g., modify it or perform a calculation).
item: The current element in the iteration.
iterable: The list (or any collection) that you are iterating through.

In [3]:
value=[]
for i in range(5):
    num=int(input("Enter the value \n"))
    value.append(num)
sum_value=[x+3 for x in value] 
print(sum_value)
 

[15, 15, 15, 15, 15]


Subtraction (-):
You can subtract arrays or a scalar from an array:

In [4]:
array1=np.array([1, 8, 3, 4])
array2=np.array([1, 2, 9, 10])
#Two method use addition two dimensional array 
addition=array1-array2  
addition2=np.subtract(array1, array2)
print("The one is addition",addition)
print("The second is addition2",addition2)

The one is addition [ 0  6 -6 -6]
The second is addition2 [ 0  6 -6 -6]


# Multiplication (*):
Element-wise multiplication is supported:
Element wise mean element by element

In [5]:
arr1=np.array([1, 2, 3])
arr2=np.array([2, 1, 3])
result = arr1 * arr2  # Element-wise multiplication
print(result)  # Output: [4 10 18]
# tow method use previous program check it
scalar_result = arr1 * 2  # Multiplying each element by a scalar
print(scalar_result)  # Output: [2 4 6]


[2 2 9]
[2 4 6]


# Division 

In [6]:
var1=np.array([10, 4])
div=var1/2
print(div)

[5. 2.]


In [7]:
var1=np.array([12, 34, 4])
var2=np.array([2, 5, 3])
division=np.divide(var1,var2)
print(division)

[6.         6.8        1.33333333]


## Modulus:

In [8]:
value=np.array([12, 13])
mod=value%2
print(mod)

[0 1]


## Two dimensional array addition

In [9]:
value1=np.array([[12, 12, 34, 32], [1, 2, 3, 4]])
value2=np.array([[11, 2, 3, 32], [1, 2, 9, 4]])
addition = np.add(value1, value2)
print(value1)
print()
print(value2)
print()
print(addition)

[[12 12 34 32]
 [ 1  2  3  4]]

[[11  2  3 32]
 [ 1  2  9  4]]

[[23 14 37 64]
 [ 2  4 12  8]]


 ##  Matrix Operations (Dot Product)
If you have 2D arrays (matrices), you can use np.dot() or @ for matrix multiplication:
The matrix multiplication result c = a @ b will have elements calculated as follows:

First row, first column: (1 * 5) + (2 * 7) = 5 + 14 = 19
First row, second column: (1 * 6) + (2 * 8) = 6 + 16 = 22
Second row, first column: (3 * 5) + (4 * 7) = 15 + 28 = 43
Second row, second column: (3 * 6) + (4 * 8) = 18 + 32 = 50

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(a, b)  # Matrix multiplication
# Or equivalently:
# result = a @ b
print(result)
# Output: [[19 22]
#          [43 50]]

[[19 22]
 [43 50]]
