## Broadcasting:
Broadcasting in NumPy refers to the ability of NumPy to perform element-wise operations on arrays of different shapes. When you perform an operation between two arrays, NumPy will automatically "broadcast" the smaller array to match the shape of the larger one, under certain conditions.
Note: mong sara broadcasting kar da de che mong sara two D array ao da mong 1 bal sara add kao no broadcast kar da de, che smaller size array da ba add kai big array sara.

In [1]:
import numpy as np
var = np.array([1, 2, 3])
var_1 = np.array([[1],[2],[3]])
print(var.shape)
print()
print(var_1.shape)
print()
print(var+var_1)

(3,)

(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [2]:
x = np.array([[12],[13]])
y = np.array([[1],[2]])
print(x)
print(x.shape)
print()
print(y)
print(y.shape)
print(" combine it")
print()
print(x+y)


[[12]
 [13]]
(2, 1)

[[1]
 [2]]
(2, 1)
 combine it

[[13]
 [15]]
