## np.concatenate()
### Purpose: Joins arrays along an existing axis.
### Syntax: np.concatenate((array1, array2, ...), axis=0)
jb hm 2 array eik dosry k sat melaty hai join karty, wo axis 0 or axis 1, axis 0 mean column and axis 1 row

### One Dimensional Array:

In [3]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
join = np.concatenate((arr1, arr2)) # Dono array eik dosro k sath concatenate karna.
print(arr1)
print()
print(arr2)
print()
print(join)

[1 2 3]

[4 5 6]

[1 2 3 4 5 6]


### Two Dimensional Array:
we are join two dimensional Array through vertical and hosrizental.

In [4]:
vr = np.array([[1, 2],[3, 4]])
vr1 = np.array([[5,6],[7,8]])
arr_new = np.concatenate((vr, vr1))
print(arr_new)
print("************")
arr_new1 = np.concatenate((vr, vr1), axis=0)
print(arr_new1)
print("+++++++++++++")
arr_new2 = np.concatenate((vr, vr1), axis=1)
print(arr_new2)





[[1 2]
 [3 4]
 [5 6]
 [7 8]]
************
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
+++++++++++++
[[1 2 5 6]
 [3 4 7 8]]


## Stack :
we are used in stack numpy, between merge two array, then row wise axis or column wise axis, height wise axis.

## np.vstack() (Vertical Stack)
Purpose: Stacks arrays vertically (row-wise), i.e., along axis 0.
Syntax: np.vstack((array1, array2, ...))


In [5]:
var1= np.array([1, 2, 3])
var2= np.array([4, 5, 6])
result = np.vstack((var1, var2))
print(result)

[[1 2 3]
 [4 5 6]]


## np.hstack() (Horizontal Stack)
Purpose: Stacks arrays horizontally (column-wise), i.e., along axis 1.
Syntax: np.hstack((array1, array2, ...))

In [6]:
x= np.array([1, 2, 3])
y= np.array([4, 5, 6])
z=np.hstack((x,y))
print(z)

[1 2 3 4 5 6]


## np.dstack() (Depth Stack)
Purpose: Stacks arrays along a new third axis (depth).
Syntax: np.dstack((array1, array2, ...))

In [7]:
xx = np.array([11, 22, 33, 44])
yy = np.array([44, 55, 66, 55])
zz=np.dstack((xx, yy))
print(zz)
print(zz.ndim)

[[[11 44]
  [22 55]
  [33 66]
  [44 55]]]
3


## Split:
split function hm jb use karty, keh one dimensional array or two dimensional array ko taqsim kary.

In [ ]:
a= np.array([1, 2, 3, 4, 5, 6])
b=np.array_split(a, 2) # b mai a ka array store hwa hai jo split hwa two dimensional array mai.
c=np.array_split(b, 2,axis=1) 
print(b)
print(c)

[array([1, 2, 3]), array([4, 5, 6])]
[array([[1],
       [4]]), array([[2],
       [5]])]
