## Iteration:
Iteration in NumPy arrays is efficient and can be done in several ways. Here are a few methods to iterate over a NumPy array:
## OR
iteration  used for we are access one by one element in array through for loop.

## One dimensional Array iteration:
We are used simple for loop.

In [ ]:
import numpy as np
var = np.array([1, 2, 3, 4])
print(var)
print()
for i in var:
 print(i)

 

## Two Dimensional Array:


In [ ]:
var1= np.array([[11, 22, 33],[33, 44, 55],[44, 66, 77]])
print(var1)
print(var1.ndim)
print()
for i in var1:
    for j in i:
        print(j)

## Three dimensional Array:

In [ ]:
var3 = np.array([[[12, 233, 44],[66, 55, 44],[5,33,22]]])
print(var3)
print(var3.ndim)
print()
## three time for loop used.
for i in var3:
    for j in i:
        for k in j:
            print(k)

## Using nditer() for Iteration
The nditer() function provides a more flexible way to iterate over arrays, especially when working with multi-dimensional arrays. It allows for more control, such as simultaneous iteration over multiple axes.
#### OR
we are used nditor control the program time and does not used for loop i.e : three dimensional array used for loop three time, and nditor used to one time for loop used.

In [ ]:
var4= np.array([[[1,2 ,3 , 4],[3, 4, 2, 2]]])
print(var4.ndim)
for i in np.nditer(var4):  # used one time for loop
    print(i)

## Using enumerate() for Index and Element
When you need both the index and the value during iteration, you can use enumerate().
ndenumerat() function used.

In [20]:
var4= np.array([[[1,2 ,3 , 4],[3, 4, 2, 2],[22, 44, 33, 22]]])
print(var4)
print(var4.ndim)
for index, data in np.ndenumerate(var4):
     print(f" Index :{index} element :{data}")
    # print(index, data)

[[[ 1  2  3  4]
  [ 3  4  2  2]
  [22 44 33 22]]]
3
 Index :(0, 0, 0) element :1
 Index :(0, 0, 1) element :2
 Index :(0, 0, 2) element :3
 Index :(0, 0, 3) element :4
 Index :(0, 1, 0) element :3
 Index :(0, 1, 1) element :4
 Index :(0, 1, 2) element :2
 Index :(0, 1, 3) element :2
 Index :(0, 2, 0) element :22
 Index :(0, 2, 1) element :44
 Index :(0, 2, 2) element :33
 Index :(0, 2, 3) element :22
