Numpy array functon 

numpy.zeros()
Definition: Creates an array filled with zeros.

In [1]:
import numpy as np
arr_zero=np.zeros((3,4)) # in these step mean 3 row and 4 column and print all zeros
print(arr_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.ones()
Definition: Creates an array filled with ones.

In [2]:
arr_one=np.ones((2,4))
print(arr_one)
print(arr_one.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


Empty: creates an array and sore the previous data 

In [3]:
arr_empty=np.empty(3)
print(arr_empty)

[5.e-324 4.e-323 0.e+000]


numpy.arange()
Definition: Returns an array with regularly spaced values within a specified range.

Explanation: This function is useful for creating sequences of numbers with a specified start, stop, and step. It’s similar to Python’s range(), but it returns a NumPy array.

In [4]:
arr_arange=np.arange(4)
print(arr_arange)

[0 1 2 3]


In [5]:
arr_arange1=np.arange(2,10,3)
print(arr_arange1)

[2 5 8]


Diagonal: digonal mean start to one the array value and eye() use.

In [6]:
arr_dia=np.eye(3,4)
print(arr_dia)
print(type(arr_dia))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
<class 'numpy.ndarray'>


Linspace: two element between space declare 

In [7]:
arr_linspace=np.linspace(1,10, num=5)
print(arr_linspace)

[ 1.    3.25  5.5   7.75 10.  ]
