Array: to create numpy array to use the function np.array()

In [1]:
import numpy as np
x=[1, 2, 3, 4]
y=np.array(x)
print(y)

[1 2 3 4]


We are enter the value through for loop and store the array

In [2]:

value=[]  #Empty list declare
for i in range(1,5): # 1 to 4 value pass n-1
    value1=int(input("Enter the value "))
    value.append(value1)  # we are store data in value variable
print(np.array(value))  # and then print the value so store the array 
#np.array mean store data in array

[12 12 12  2]


Types of Numpy Array:
One Dimensional Array 1D/ 1's= array1=np.array([1, 2, 3, 4])
Two Dimesional Array 2D/2's =  array2=np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
Three dimesional Array 3D/3's = array3=np.array([[[11, 22, 33, 44],[5, 6, 7, 8],[1, 2, 3, 4]]])

Main point we are check the dimmesional of array we are use the (ndim) i.e arr=np.array([1, 3, 5])
                                                                           print(arr.ndim)
                                                                           

ONE DIMENSIONAL ARRAY

In [3]:
array1=np.array([1, 2, 3, 4])
print(array1)
print(array1.ndim)

[1 2 3 4]
1


TWO DIMENSIONAL ARRAY

In [4]:
array2=np.array([[1, 2, 3, 4], [11, 22, 33, 44]])
print(array2)
print(array2.ndim)

[[ 1  2  3  4]
 [11 22 33 44]]
2


THREE DIMESIONAL ARRAY

In [5]:
array3=np.array([[[1, 2, 3, 4],[12, 13, 14, 14],[11, 21, 22, 12]]])
print(array3)
print(array3.ndim)

[[[ 1  2  3  4]
  [12 13 14 14]
  [11 21 22 12]]]
3


like we are check the ten dimensionsal array

In [6]:
array10=np.array([1, 2, 3, 4], ndmin=10)
print(array10)
print(array10.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


THREE DIMENSIONAL data pass through keyboard

In [7]:
value = []  # Empty list to store values
for i in range(1, 5):  # 1 to 4 values
    value1 = int(input("Enter the value: "))  # Get user input
    value.append(value1)  # Store each value

# Convert the list to a NumPy array and reshape it to 3D (e.g., shape (2, 2, 1))
three_dim_array = np.array(value).reshape(2, 2, 1)

print("3D Array:")
print(three_dim_array)

ValueError: invalid literal for int() with base 10: ''