## Shape:
The shape attribute of a NumPy array gives you the dimensions of the array (i.e., the number of elements along each axis). It returns a tuple representing the size of the array along each dimension.
And use shape function.

In [1]:
import numpy as np
var=np.array([1, 2, 4])
print(var.shape)

(3,)


In [2]:
var1=np.array([[2,3 , 5],[5, 3, 5]])
print(var1)
print()
print(var1.shape)
print(np.ndim(var1)) # we are check the dimensional

[[2 3 5]
 [5 3 5]]

(2, 3)
2


In [3]:
var=np.array([1, 2, 3], ndmin=4) #ndmin mean in this array convert to four dimensional array
print(var)
print(var.shape) #output 1, 1, 1, 3 > three one mean first three bracket in array

[[[[1 2 3]]]]
(1, 1, 1, 3)


## Reshape:
The reshape() function allows you to change the shape of an array without changing its data. It returns a new array with the specified shape, as long as the total number of elements matches the original shape.
And use reshape function.

In [4]:
varr=np.array([1, 2, 4, 5, 6, 7, 8, 9])
print(varr)
print(varr.ndim)
print()
x=varr.reshape(2,4) # in this array conver to two row and 4 column
print(x)
print(x.ndim)

[1 2 4 5 6 7 8 9]
1

[[1 2 4 5]
 [6 7 8 9]]
2


In [5]:
var=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13])
y=var.reshape(2, 3, 2) #  2 mean two dimensional, 3 row, 2 column
print(y)
print(y.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 13]]]
3


We are conver in previous program three dimensional array  to one dimensional array 

In [6]:
var=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13])
y=var.reshape(2, 3, 2) #  2 mean two dimensional, 3 row, 2 column
print(y)
print(y.ndim)
print()
x=y.reshape(-1) # -1 mean conver to one dimensioal array or previous array 
print(x)
print(x.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 13]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 13]
1
