## Indexing:
Finding the indexing of one, two, and three dimensional array

## One dimensional Array:

In [1]:
import numpy as np
var=np.array([1, 2, 3, 5])
print(var[2])

3


## Two dimensional Array:
Two point of two dimensional array.[[]] the first the dimensional we are used 0 and second is 1.

In [2]:
var1=np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(var1)
print()
print(var1[0, 2]) # 0 mean dimensional one and two mean index 2
print()
print(var1[1,3]) #1 mean dimensional two and three mean index 3

[[1 2 3 4]
 [5 6 7 8]]

3

8


## Three Dimensional Array:
Indexing in a 3D NumPy array is similar to indexing in 2D arrays, but with an additional dimension. A 3D array has the shape (depth, rows, columns). Here’s how you can index it:

In [3]:
arr = np.array([[[1, 2], [3, 4]], 
                [[5, 6], [7, 8]]])
print(arr)
print(arr.ndim)
print()
print(arr[0,1,1]) # 0 mean dimensional 1, one mean rwo 2=[3, 4], index 1.
print(arr[1,0,1]) # 1 mean dimensional 2, 0 mean row 1=[5,6], index 1.


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3

4
6


In [4]:
arr = np.array([[[1, 3, 5],[23, 45, 65]],
                [[0, 00, 000],[99, 89, 54]],
                [[22, 11, 22], [4, 3, 2]]])
print(arr)
print(arr.ndim)
print()
print(arr[0,1,1]) # 0 mean dimensional 1, one mean rwo 2=[3, 4], index 1.
print(arr[1,0,1]) # 1 mean dimensional 2, 0 mean row 1=[5,6], index 1.
print(arr[2,1,2]) # 2 mean dimensional 3, 1 mean row 2, index 2. 


[[[ 1  3  5]
  [23 45 65]]

 [[ 0  0  0]
  [99 89 54]]

 [[22 11 22]
  [ 4  3  2]]]
3

45
0
2


## Slicing in array:
Slicing in NumPy allows you to access a specific range of elements from an array. It’s similar to Python lists but with additional features. Here's how slicing works in NumPy:
### Basic syntex:
array[start:stop:step]
start: The index where slicing starts (inclusive).
stop: The index where slicing stops (exclusive).
step: The step size between indices (optional, default is 1).

In [5]:
var=np.array([99, 55, 3, 4, 55, 3])
print(var)
print()
print("99 to 55 ",var[0:5])

[99 55  3  4 55  3]

99 to 55  [99 55  3  4 55]


## Two Dimensional Array:

In [6]:
var1=np.array([[1, 2, 3, 4, 5], [3, 5, 6, 7, 8],[12, 2, 3, 44, 33]])
print(var1)
print()
print(" print the row one 2 to 4 value", var1[0,1:4])   # 0 mean row 1, index 1 start to index 4-1
print(" print the value of row 2, 6 to 8",var1[1,2:])   # 1 mean row 2, idext 2 start last tak
print(" print the value of row 3, 44 to 33",var1[2,3:]) #2 mean row 3, index 3 start to last tak. 

[[ 1  2  3  4  5]
 [ 3  5  6  7  8]
 [12  2  3 44 33]]

 print the row one 2 to 4 value [2 3 4]
 print the value of row 2, 6 to 8 [6 7 8]
 print the value of row 3, 44 to 33 [44 33]


## Using Step in Slicing:
start, stop, step. step mean element number, i.e : [1:6: 2] index 1 then index 3 index 5 etc

In [7]:
step = np.array([11, 2, 4, 66, 7, 78, 54, 67, 88, 44])
print("print the value of 4 to 88 tak, beween in 2 step", step[2: 9:2]) # output : 4, 7, 54, 88

print the value of 4 to 88 tak, beween in 2 step [ 4  7 54 88]
