## Matrix:
### Matrix in NumPy:
To create a matrix in NumPy, you can either use the numpy.matrix class or create a 2D array (which is more common).

In [1]:
import numpy as np
var = np.matrix([1, 2, 3, 4])
print(var)

[[1 2 3 4]]


Array:

In [2]:
var1 =np.array([1, 2, 3, 4])
print(var1)

[1 2 3 4]


## Array and Matrix:
In this case, the numpy.array is more flexible and works with a wider range of functions. numpy.matrix is limited in terms of the functions it supports, and many people prefer to work with ndarray for matrix-like operations.

## Matrix Functions in NumPy:
NumPy provides a variety of functions to perform matrix-related operations. Some of the common ones include:

### Matrix Multiplication:
use dot() for matrix.

In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)  # Matrix multiplication
print(result)
print(A)
print()
print(B)

[[19 22]
 [43 50]]
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


## Matrix:
 Transpose: You can transpose a matrix using .T.
 Transpose mean ulta the origional matrix.

In [4]:
x = np.matrix([[1, 2],[3, 4]])
y = np.transpose(x)
print(x) # origional array
print()
print(y) # transpose array
print()
print(x.T) # Short cut 

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]

[[1 3]
 [2 4]]


### swapaxes():
transpose and swapaxes same work but swapaxes change the dimensional.

In [5]:
arr = np.matrix([[1, 2],[3, 4]])
print(arr)
print()
print(np.swapaxes(arr, 0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [6]:
one = np.matrix([[3,2],[1,4]])
print(one)
print()
print(np.linalg.inv(one))

[[3 2]
 [1 4]]

[[ 0.4 -0.2]
 [-0.1  0.3]]


In [7]:
two = np.matrix([[10, 3],[5,2]])
# inverse = np.linalg.inv(two) # first cross multiplication then cross multiplication divide by element.
print(two)
print(np.linalg.inv(two))

[[10  3]
 [ 5  2]]
[[ 0.4 -0.6]
 [-1.   2. ]]


## Three dimensional Determinant:


In [8]:
var = np.matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(var)
print()
print(np.linalg.det(var))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

0.0
