## Insert & Delate:
insert() and delete() functions. Both functions allow you to modify the array by adding or removing elements at specific positions.


## insert()
### Purpose:
Inserts values into an array at specified indices.
### Syntax:
numpy.insert(arr, obj, values, axis=None)

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x=np.insert(arr, 2, [12, 34])
print(arr)
print(x)

[1 2 3 4 5]
[ 1  2 12 34  3  4  5]


### Two Dimensional Array Insert:

In [2]:
x = np.array([[1,2, 3],[4, 5, 6]])
y = np.insert(x, 2, [11, 22], axis=1) # axis mean column site value store
print(x)
print()
print(y)

[[1 2 3]
 [4 5 6]]

[[ 1  2 11  3]
 [ 4  5 22  6]]


appened be used, to store data.

In [3]:
x1 = np.array([[1, 2], [3, 4]])
y1 = np.append(x1, [[12, 13]],axis=0) # appened value store at the last index.
print(x1)
print()
print(y1)

[[1 2]
 [3 4]]

[[ 1  2]
 [ 3  4]
 [12 13]]


## Delate:
### numpy.delete()
Purpose: Deletes elements from an array at specified indices.
### Syntax:
numpy.delete(arr, obj, axis=None

In [4]:
array_1 = np.array([1, 2, 3, 4, 5, 6])
array_2 = np.delete(array_1, 2)        # index 2 delate
array_3 = np.delete(array_1, [0,2,4])  # 1, 3, 5 delate 
print(array_1)
print()
print(array_2)
print(array_3)

[1 2 3 4 5 6]

[1 2 4 5 6]
[2 4 6]
